sudo: required
dist: xenial
language: python

python:
  - "3.6"

env:
  - SECRET_KEY=secretkey

install:
  - pip install pipenv
  - pipenv sync --dev

before_script:
  - pipenv run src/manage.py migrate

script:
  - pipenv run src/manage.py test src/
  - pipenv run flake8