# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='comment',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='room',
            field=models.CharField(default='SCH1', max_length=255),
            preserve_default=False,
        ),
    ]
