# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer_app', '0002_auto_20161017_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='type',
            field=models.CharField(choices=[('BW', 'Fekete-fehér'), ('CL', 'Színes')], max_length=2),
        ),
    ]
