# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-14 20:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printer_app', '0005_remove_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('uploaded', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='printer',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='type',
            field=models.CharField(choices=[('BW', 'Black-White'), ('CL', 'Color')], max_length=2, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='room',
            field=models.CharField(default='', max_length=255, verbose_name='Room number'),
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='file',
            name='shared_with',
            field=models.ManyToManyField(related_name='shared_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
