# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer_app', '0005_auto_20161024_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='type',
            field=models.CharField(choices=[('BW', 'Black-White'), ('CL', 'Color')], max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
