# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printer_app', '0006_auto_20161024_2058'),
        ('printer_app', '0006_auto_20161114_1955'),
    ]

    operations = [
    ]
