# Generated by Django 2.0.4 on 2018-04-30 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_files', to='account.Profile')),
                ('shared_with', models.ManyToManyField(related_name='shared_files', to='account.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('type', models.CharField(choices=[('BW', 'Black-White'), ('CL', 'Color')], max_length=2, verbose_name='Type')),
                ('status', models.BooleanField(default=False, verbose_name='Available')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_printers', to='account.Profile')),
            ],
        ),
    ]
