# Generated by Django 2.0.4 on 2018-05-26 23:22

import dashboard.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='', validators=[dashboard.validators.FileSizeValidator(52428800)]),
        ),
        migrations.AlterField(
            model_name='file',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_files', to='account.Profile'),
        ),
    ]
