# Generated by Django 2.0.4 on 2018-05-26 23:42

import dashboard.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180526_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='', validators=[dashboard.validators.FileSizeValidator(52428800), django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'odt', 'djvu', 'jpg', 'jpeg', 'pdf', 'png'])]),
        ),
    ]
